### PR TITLE
allow_editing_local_users

### PR DESCRIPTION
**Pull request by odelaere**

### CODE REVIEW

**Comment by bsuttor** [comment]
Why do you want to edit user ? Email and fullname should be get by SSO

**Comment by odelaere** [comment]
@bsuttor because some user are plain old local plone user.
We use it to separate admin account and working account of our customers with the "app managers" profile.
Since it's the same person with 2 accounts. I don't thing it will be possible via SSO.

On the other hand I don't think giving a permanent admin or admin-like access right to "app managers" is a good idea.

**Comment by bsuttor** [comment]
ok, I didn't see it's only for user in acl_users/source_users, so LGTM, can you rebase you PR with master ?

**Comment by bsuttor** [comment]
ok, I didn't see it's only for user in acl_users/source_users, so LGTM, can you rebase you PR with master ?

**Pull request merged**
